import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy | SLAB Voice',
  description: 'Privacy Policy for SLAB Voice — AI-powered sales call transcription and analytics.',
}

export default function PrivacyPolicy() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 prose prose-slate">
      <h1>Privacy Policy</h1>
      <p>Last updated: March 17, 2026</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the collection, use and
        disclosure of Your information when You use the Service and tells You about Your privacy
        rights and how the law protects You.
      </p>
      <p>
        We use Your Personal Data to provide and improve the Service. By using the Service, You
        agree to the collection and use of information in accordance with this Privacy Policy.
      </p>

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words whose initial letters are capitalized have meanings defined under the following
        conditions. The following definitions shall have the same meaning regardless of whether they
        appear in singular or in plural.
      </p>
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created for You to access our Service or
          parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under
          common control with a party, where &quot;control&quot; means ownership of 50% or more of
          the shares, equity interest or other securities entitled to vote for election of directors
          or other managing authority.
        </li>
        <li>
          <strong>Application</strong> refers to SLAB, the software program provided by the Company.
        </li>
        <li>
          <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;,
          &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to SLAB LLC, 2295 E 4078
          N Filer, ID 83328.
        </li>
        <li>
          <strong>Country</strong> refers to: Idaho, United States
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service such as a computer, a
          cell phone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information
          that relates to an identified or identifiable individual. We use &quot;Personal Data&quot;
          and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.
        </li>
        <li>
          <strong>Service</strong> refers to the Application.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person who processes the data
          on behalf of the Company. It refers to third-party companies or individuals employed by
          the Company to facilitate the Service, to provide the Service on behalf of the Company, to
          perform services related to the Service or to assist the Company in analyzing how the
          Service is used.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, either generated by
          the use of the Service or from the Service infrastructure itself (for example, the
          duration of a page visit).
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the Service, or the company,
          or other legal entity on behalf of which such individual is accessing or using the
          Service, as applicable.
        </li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain personally identifiable
        information that can be used to contact or identify You. Personally identifiable information
        may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
      </ul>

      <h4>Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device&apos;s Internet Protocol address
        (e.g. IP address), browser type, browser version, the pages of our Service that You visit,
        the time and date of Your visit, the time spent on those pages, unique device identifiers
        and other diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may collect certain
        information automatically, including, but not limited to, the type of mobile device You use,
        Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your mobile
        operating system, the type of mobile Internet browser You use, unique device identifiers and
        other diagnostic data.
      </p>

      <h4>Information Collected while Using the Application</h4>
      <p>
        While using Our Application, in order to provide features of Our Application, We may
        collect, with Your prior permission:
      </p>
      <ul>
        <li>
          Audio recordings captured through Your Device&apos;s microphone for the purposes of
          transcription, analysis, and sales training feedback.
        </li>
        <li>Pictures and other information from your Device&apos;s camera and photo library.</li>
      </ul>
      <p>
        We use this information to provide features of Our Service, to improve and customize Our
        Service. The information may be uploaded to the Company&apos;s servers and/or a Service
        Provider&apos;s server or it may be simply stored on Your device.
      </p>
      <p>
        You can enable or disable access to this information at any time, through Your Device
        settings.
      </p>

      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>
          <strong>To provide and maintain our Service</strong>, including to monitor the usage of
          our Service.
        </li>
        <li>
          <strong>To manage Your Account:</strong> to manage Your registration as a user of the
          Service.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> the development, compliance and
          undertaking of the purchase contract for the products, items or services You have
          purchased or of any other contract with Us through the Service.
        </li>
        <li>
          <strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other
          equivalent forms of electronic communication regarding updates or informative
          communications related to the functionalities, products or contracted services.
        </li>
        <li>
          <strong>To provide You</strong> with news, special offers, and general information about
          other goods, services and events which We offer.
        </li>
        <li>
          <strong>To manage Your requests:</strong> To attend and manage Your requests to Us.
        </li>
        <li>
          <strong>For business transfers:</strong> We may use Your Personal Data to evaluate or
          conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale
          or transfer of some or all of Our assets.
        </li>
        <li>
          <strong>For other purposes</strong>: We may use Your information for other purposes, such
          as data analysis, identifying usage trends, and to evaluate and improve our Service.
        </li>
      </ul>

      <p>We may share Your Personal Data in the following situations:</p>
      <ul>
        <li>
          <strong>With Service Providers:</strong> We may share Your Personal Data with Service
          Providers to monitor and analyze the use of our Service, to contact You.
        </li>
        <li>
          <strong>For business transfers:</strong> We may share or transfer Your Personal Data in
          connection with any merger, sale of Company assets, financing, or acquisition.
        </li>
        <li>
          <strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in
          which case we will require those affiliates to honor this Privacy Policy.
        </li>
        <li>
          <strong>With business partners:</strong> We may share Your Personal Data with Our business
          partners to offer You certain products, services or promotions.
        </li>
        <li>
          <strong>With Your consent</strong>: We may disclose Your Personal Data for any other
          purpose with Your consent.
        </li>
      </ul>

      <h3>Retention of Your Personal Data</h3>
      <p>
        The Company will retain Your Personal Data only for as long as is necessary for the purposes
        set out in this Privacy Policy. We will retain and use Your Personal Data to the extent
        necessary to comply with our legal obligations, resolve disputes, and enforce our legal
        agreements and policies.
      </p>
      <ul>
        <li>
          <strong>Account Information:</strong> retained for the duration of your account
          relationship plus up to 24 months after account closure.
        </li>
        <li>
          <strong>Customer Support Data:</strong> support tickets and chat transcripts up to 24
          months from closure.
        </li>
        <li>
          <strong>Usage Data:</strong> application usage statistics and server logs up to 24 months.
        </li>
      </ul>
      <p>
        We may retain Personal Data beyond these periods where required by legal obligation, to
        establish or defend legal claims, at Your explicit request, or due to technical backup
        limitations.
      </p>

      <h3>Transfer of Your Personal Data</h3>
      <p>
        Your information, including Personal Data, is processed at the Company&apos;s operating
        offices and in any other places where the parties involved in the processing are located.
        The Company will take all steps reasonably necessary to ensure that Your data is treated
        securely and in accordance with this Privacy Policy.
      </p>

      <h3>Delete Your Personal Data</h3>
      <p>
        You have the right to delete or request that We assist in deleting the Personal Data that We
        have collected about You. You may do so by signing in to Your Account and visiting the
        account settings section, or by contacting Us directly.
      </p>

      <h3>Disclosure of Your Personal Data</h3>
      <h4>Business Transactions</h4>
      <p>
        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
        transferred. We will provide notice before Your Personal Data is transferred and becomes
        subject to a different Privacy Policy.
      </p>
      <h4>Law Enforcement</h4>
      <p>
        Under certain circumstances, the Company may be required to disclose Your Personal Data if
        required to do so by law or in response to valid requests by public authorities.
      </p>
      <h4>Other Legal Requirements</h4>
      <p>
        The Company may disclose Your Personal Data in the good faith belief that such action is
        necessary to:
      </p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h3>Security of Your Personal Data</h3>
      <p>
        The security of Your Personal Data is important to Us, but remember that no method of
        transmission over the Internet, or method of electronic storage is 100% secure. While We
        strive to use commercially reasonable means to protect Your Personal Data, We cannot
        guarantee its absolute security.
      </p>

      <h2>Children&apos;s Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 16. We do not knowingly collect
        personally identifiable information from anyone under the age of 16. If You are a parent or
        guardian and You are aware that Your child has provided Us with Personal Data, please
        contact Us.
      </p>

      <h2>Links to Other Websites</h2>
      <p>
        Our Service may contain links to other websites that are not operated by Us. We strongly
        advise You to review the Privacy Policy of every site You visit. We have no control over and
        assume no responsibility for the content, privacy policies or practices of any third party
        sites or services.
      </p>

      <h2>Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You of any changes by
        posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date
        at the top of this Privacy Policy.
      </p>

      <h2>Related Policies</h2>
      <p>
        For information about your rights and responsibilities when using SLAB Voice, please also
        review our <Link href="/terms">Terms of Service</Link>.
      </p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul>
        <li>
          By email:{' '}
          <a href="mailto:duncan@slabtraining.com">duncan@slabtraining.com</a>
        </li>
        <li>
          By visiting our website:{' '}
          <a href="http://www.slabtraining.com" target="_blank" rel="noopener noreferrer">
            http://www.slabtraining.com
          </a>
        </li>
        <li>By phone: (208) 212-6891</li>
      </ul>
    </div>
  );
}
